spring.application.name=excel

# File paths configuration - relative to JAR location
invoice.header.file=src/clientDetails.xlsx
invoice.items.file=src/invoiceDetails.xlsx
invoice.template.path=src/invoice_template.xlsx
invoice.template2.path=src/invoice_template_2.xlsx
invoice.output.directory=destination/